[build]
  publish = "."
  functions = "netlify/Functions"
  # This command runs our script to inject the Firebase API key into index.html
  command = "node Scripts/inject-firebase-api-key.js" 

# No changes needed for functions or redirects for this fix.
